// THE SELF-MAP — the repository tree, derived from the repository.
//
// KP's ⚛ word, 2026-08-13: "the file manifest can be used to create the tree
// instead of displaying the content."
//
// And this repo's own `docs/DOC-CLASSES.md` had already ruled it, under the
// heading *Self-maps are generated, not hand-kept*:
//
//   "A repo's structure.md (tree + manifest) is MIRROR-class where the 'truth'
//    is the repository tree itself: regenerated by tooling, never trusted to
//    memory. Hand-maintained manifests lag reality — measured in this very
//    repo, 2026-07-17 (two files missing from its own map)."
//
// So no ASCII tree is stored, drawn, or refreshed by any hand. The glob below
// IS the manifest, and the tree is drawn from it at render time. It cannot lag
// reality, because it has no copy of reality to lag behind.
//
// SCOPE, STATED RATHER THAN LEFT TO BE DISCOVERED: text-bearing files only.
// Binary assets — the icon set the generator cuts — are named as a collapsed
// line, never listed and never silently dropped. A map that hides what it left
// out is worse than a short one. (This comment once typed that set's count —
// 157 — and the disk held 52: the one hand-kept number in the app, and it was
// wrong, which is the law proving itself. Taken out 2026-08-23; no count is
// typed anywhere in this app now. Counts are read, at render, from the glob.)
//
// NOT THE REPOSITORY, and so not the map: dependencies, build output, Tauri's
// generated and compiled trees. The same set scripts/derive.mjs excludes when
// it redraws structure.md — one rule, two readers.

const KEYS = Object.keys(
	import.meta.glob('/**/*.{md,json,js,mjs,ts,svelte,css,html,rs,toml,txt,yml,yaml}', {
		eager: false,
	}),
)
	.map((k) => k.replace(/^\//, ''))
	.filter(
		(k) =>
			!k.startsWith('node_modules/') &&
			!k.startsWith('.svelte-kit/') &&
			!k.startsWith('build/') &&
			!k.startsWith('src-tauri/target/') &&
			!k.startsWith('src-tauri/gen/'),
	)
	.sort();

export interface Node {
	name: string;
	path: string;
	dir: boolean;
	children: Node[];
}

function insert(root: Node, parts: string[], full: string): void {
	if (parts.length === 0) return;
	const [head, ...rest] = parts;
	const isDir = rest.length > 0;
	let node = root.children.find((c) => c.name === head && c.dir === isDir);
	if (!node) {
		node = {
			name: head,
			path: isDir ? full.slice(0, full.indexOf(head) + head.length) : full,
			dir: isDir,
			children: [],
		};
		root.children.push(node);
	}
	insert(node, rest, full);
}

export const ROOT: Node = (() => {
	const root: Node = { name: 'resonance-standards', path: '', dir: true, children: [] };
	for (const k of KEYS) insert(root, k.split('/'), k);
	const order = (n: Node): void => {
		n.children.sort((a, b) =>
			a.dir !== b.dir ? (a.dir ? -1 : 1) : a.name.localeCompare(b.name),
		);
		n.children.forEach(order);
	};
	order(root);
	return root;
})();

/** Box-drawing lines, drawn from the live tree — never stored anywhere. */
export function draw(node: Node = ROOT, prefix = '', isRoot = true): string[] {
	const out: string[] = [];
	if (isRoot) out.push(node.name + '/');
	node.children.forEach((child, i) => {
		const last = i === node.children.length - 1;
		out.push(prefix + (last ? '└── ' : '├── ') + child.name + (child.dir ? '/' : ''));
		if (child.dir) out.push(...draw(child, prefix + (last ? '    ' : '│   '), false));
	});
	return out;
}

export const TREE_COUNTS = {
	files: KEYS.length,
	folders: (function count(n: Node): number {
		return n.children.reduce((acc, c) => acc + (c.dir ? 1 + count(c) : 0), 0);
	})(ROOT),
};

/**
 * A paper that declares itself a self-map gets the LIVE tree instead of its own
 * stored copy. Detected by the repo's own vocabulary, never by filename — the
 * rule is the doc class, so any future self-map inherits it by saying so.
 */
export function isSelfMap(text: string): boolean {
	return /MIRROR-class self-map/i.test(text);
}
