<script lang="ts">
	// THE PAPERS ROOM — this repository, reading itself.
	//
	// KP's ⚛ law, 2026-08-13: "we want to be sure the app is reading what
	// exists not hardcoding values so there is nothing extra to maintain."
	//
	// There is no list of documents in this file and there never will be.
	// `$lib/papers` globs the repo at build; the groups below ARE the folders
	// and the titles ARE each file's own first heading. Add a standard, and it
	// is in this room the next time the app builds — nobody edits anything.
	//
	// Rendered by the escape-first markdown telling, MIRRORED from
	// resonance-awen/standalone/ — one definition, never a second copy.
	import { GROUPS, COUNTS } from '$lib/papers';
	import { renderMarkdown } from '$lib/markdown';
	import { draw, isSelfMap, TREE_COUNTS } from '$lib/tree';

	let wornGroup = $state(0);
	let wornPaper = $state(0);

	const group = $derived(GROUPS[wornGroup] ?? GROUPS[0]);
	const paper = $derived(group?.papers[wornPaper] ?? group?.papers[0]);
	const rendered = $derived(paper ? renderMarkdown(paper.text) : '');

	// A paper that declares itself a self-map is shown as the LIVE tree, drawn
	// from the repository, instead of the copy it happens to be carrying.
	// This repo's own DOC-CLASSES.md rules it: "regenerated by tooling, never
	// trusted to memory. Hand-maintained manifests lag reality — measured in
	// this very repo." Detected by the doc class it declares, never by filename.
	const selfMap = $derived(paper ? isSelfMap(paper.text) : false);
	const treeLines = $derived(selfMap ? draw() : []);

	function wearGroup(i: number): void {
		wornGroup = i;
		wornPaper = 0;
	}
</script>

<svelte:head>
	<title>Standards — the papers</title>
</svelte:head>

<section class="docs">
	<header class="docs__head">
		<h1>The standards</h1>

		<!-- Counted from the glob, never typed. If this number is wrong, the
		     repository changed and the room already knows. -->
		<p class="tally">
			{COUNTS.papers} papers · {COUNTS.groups} folders · {(COUNTS.bytes / 1024).toFixed(0)} KB,
			read from this repository's own ground
		</p>

		<!-- The folders ARE the groups. A new folder becomes a tab by existing. -->
		<div class="docs__tabs" role="tablist" aria-label="Folders">
			{#each GROUPS as g, i (g.folder)}
				<button
					class="tab"
					class:worn={i === wornGroup}
					role="tab"
					aria-selected={i === wornGroup}
					onclick={() => wearGroup(i)}
				>
					{g.label}<span class="tab__n">{g.papers.length}</span>
				</button>
			{/each}
		</div>

		<!-- The papers of the worn folder, titled by their own first heading. -->
		<div class="docs__tabs docs__tabs--papers" role="tablist" aria-label="Papers">
			{#each group.papers as p, i (p.path)}
				<button
					class="tab tab--paper"
					class:worn={i === wornPaper}
					role="tab"
					aria-selected={i === wornPaper}
					onclick={() => (wornPaper = i)}
					title={p.path}
				>
					{p.title}
				</button>
			{/each}
		</div>

		{#if paper}
			<p class="whence">
				<code>{paper.path}</code>{#if paper.blurb}<span class="whence__blurb"
						>{paper.blurb}</span
					>{/if}
			</p>
		{/if}
	</header>

	{#if selfMap}
		<!-- The self-map, drawn live. Nothing here is stored: the tree is built
		     from the repository's own file list at render time, so it cannot
		     lag reality — it has no copy of reality to lag behind. -->
		<article class="md-body">
			<h1>The repository, as it stands</h1>
			<p class="tree-note">
				Drawn live from this repository — <strong>{TREE_COUNTS.files} text files</strong>
				across <strong>{TREE_COUNTS.folders} folders</strong>. Binary assets (the cut icon
				set) are excluded and named here rather than dropped in silence.
				<em>MIRROR-class self-map: regenerated by tooling, never trusted to memory.</em>
			</p>
			<pre class="tree">{treeLines.join('\n')}</pre>
		</article>
	{:else}
		<!-- Rendered by the mirrored escape-first telling; the source is this
		     repository's own papers, so the html below is ours end to end. -->
		<article class="md-body">
			{@html rendered}
		</article>
	{/if}
</section>

<style>
	.docs {
		max-width: 960px;
		margin: 0 auto;
		padding: 1.25rem 1rem calc(64px + env(safe-area-inset-bottom, 0px));
	}

	.docs__head h1 {
		font-size: 1.35rem;
		margin: 0 0 0.75rem;
		color: var(--text);
	}

	/* A true tab strip: always across the top, scrolling sideways when the
	   land is narrow — never stacking. */
	.docs__tabs {
		display: flex;
		flex-wrap: nowrap;
		overflow-x: auto;
		gap: 0.4rem;
		margin-bottom: 1rem;
		padding-bottom: 0.25rem;
	}

	.tab {
		flex: 0 0 auto;
		white-space: nowrap;
		font-size: 0.78rem;
		padding: 0.35rem 0.7rem;
		border-radius: 999px;
		border: 1px solid var(--border-color);
		background: none;
		color: var(--text-secondary);
		cursor: pointer;
		transition: background-color 0.15s ease, color 0.15s ease;
	}

	.tab:hover {
		background-color: var(--bg-surface);
		color: var(--text);
	}

	.tab.worn {
		background-color: var(--accent);
		border-color: var(--accent);
		color: #fff;
	}

	/* ——— The GitHub-like body ——— */
	.md-body {
		background-color: var(--bg-surface);
		border: 1px solid var(--border-color);
		border-radius: 10px;
		padding: 1.5rem 1.75rem;
		font-size: 0.92rem;
		line-height: 1.6;
		color: var(--text);
		word-break: break-word;
	}

	.md-body :global(h1),
	.md-body :global(h2) {
		margin: 1.4rem 0 0.7rem;
		padding-bottom: 0.3rem;
		border-bottom: 1px solid var(--border-color);
		line-height: 1.3;
	}

	.md-body :global(h1) {
		font-size: 1.5rem;
	}

	.md-body :global(h1:first-child) {
		margin-top: 0;
	}

	.md-body :global(h2) {
		font-size: 1.25rem;
	}

	.md-body :global(h3) {
		font-size: 1.05rem;
		margin: 1.2rem 0 0.5rem;
	}

	.md-body :global(h4),
	.md-body :global(h5),
	.md-body :global(h6) {
		font-size: 0.95rem;
		margin: 1rem 0 0.4rem;
	}

	.md-body :global(p) {
		margin: 0 0 0.8rem;
	}

	.md-body :global(a) {
		color: var(--accent);
		text-decoration: none;
	}

	.md-body :global(a:hover) {
		text-decoration: underline;
	}

	.md-body :global(code) {
		background-color: color-mix(in srgb, var(--text) 8%, transparent);
		border-radius: 5px;
		padding: 0.1em 0.35em;
		font-size: 0.85em;
	}

	.md-body :global(pre.md-code) {
		background-color: color-mix(in srgb, var(--text) 6%, transparent);
		border: 1px solid var(--border-color);
		border-radius: 8px;
		padding: 0.8rem 1rem;
		overflow-x: auto;
		margin: 0 0 0.9rem;
	}

	.md-body :global(pre.md-code code) {
		background: none;
		padding: 0;
		font-size: 0.82rem;
		line-height: 1.5;
	}

	.md-body :global(blockquote) {
		margin: 0 0 0.9rem;
		padding: 0.1rem 0 0.1rem 1rem;
		border-left: 3px solid var(--border-color);
		color: var(--text-secondary);
	}

	.md-body :global(ul),
	.md-body :global(ol) {
		margin: 0 0 0.8rem;
		padding-left: 1.5rem;
	}

	.md-body :global(li) {
		margin: 0.2rem 0;
	}

	.md-body :global(hr) {
		border: none;
		border-top: 1px solid var(--border-color);
		margin: 1.4rem 0;
	}

	.md-body :global(img) {
		max-width: 100%;
		vertical-align: middle;
	}

	.md-body :global(.md-table-holder) {
		overflow-x: auto;
		margin: 0 0 1rem;
	}

	.md-body :global(table) {
		border-collapse: collapse;
		font-size: 0.85rem;
		width: 100%;
	}

	.md-body :global(th),
	.md-body :global(td) {
		border: 1px solid var(--border-color);
		padding: 0.4rem 0.65rem;
		text-align: left;
		vertical-align: top;
	}

	/* First columns are keys — dates, names, numbers — and never squish. */
	.md-body :global(th:first-child),
	.md-body :global(td:first-child) {
		white-space: nowrap;
	}

	.md-body :global(th) {
		background-color: color-mix(in srgb, var(--text) 6%, transparent);
		font-weight: 600;
	}

	.md-body :global(tbody tr:nth-child(2n)) {
		background-color: color-mix(in srgb, var(--text) 6%, transparent);
	}

	/* The eyes walk entries by stripe — lists too. */
	.md-body :global(ul > li:nth-child(2n)),
	.md-body :global(ol > li:nth-child(2n)) {
		background-color: color-mix(in srgb, var(--text) 4%, transparent);
		border-radius: 6px;
	}

	/* Log entries: one stamped line each, striped in pairs. */
	.md-body :global(.md-log) {
		margin: 0;
		padding: 0.28rem 0.5rem;
		border-radius: 6px;
		font-size: 0.85rem;
		line-height: 1.5;
	}

	.md-body :global(.md-log--alt) {
		background-color: color-mix(in srgb, var(--text) 5%, transparent);
	}

	.md-body :global(.md-log__stamp) {
		color: var(--accent);
		font-variant-numeric: tabular-nums;
		white-space: nowrap;
	}

	/* Remote badges as quiet chips — drawn locally, never fetched. */
	.md-body :global(.md-badge) {
		display: inline-block;
		font-size: 0.7rem;
		padding: 0.12rem 0.55rem;
		margin: 0 0.15rem 0.15rem 0;
		border: 1px solid var(--border-color);
		border-radius: 999px;
		background-color: color-mix(in srgb, var(--accent) 10%, transparent);
		color: var(--text-secondary);
	}

	/* ——— This room's own additions: a second strip, and the provenance line ——— */
	.tally {
		margin: 0 0 0.9rem;
		font-size: 0.78rem;
		color: var(--text-secondary);
	}

	.docs__tabs--papers {
		margin-bottom: 0.6rem;
	}

	.tab__n {
		display: inline-block;
		margin-left: 0.4rem;
		font-size: 0.68rem;
		opacity: 0.65;
	}

	.tab--paper {
		font-size: 0.74rem;
	}

	/* The address of what you are reading, always shown — a paper without a
	   path is a claim you cannot check. */
	.whence {
		margin: 0 0 1rem;
		font-size: 0.74rem;
		color: var(--text-secondary);
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem;
		align-items: baseline;
	}

	.whence code {
		font-size: 0.72rem;
		padding: 0.1rem 0.4rem;
		border-radius: 4px;
		background-color: color-mix(in srgb, var(--accent) 10%, transparent);
	}

	.whence__blurb {
		font-style: italic;
		opacity: 0.85;
	}
	/* ——— The live self-map ——— */
	.tree-note {
		font-size: 0.78rem;
		color: var(--text-secondary);
		margin: 0 0 1rem;
	}

	.tree {
		font-family: ui-monospace, Consolas, monospace;
		font-size: 0.76rem;
		line-height: 1.55;
		white-space: pre;
		overflow-x: auto;
		margin: 0;
		padding: 1rem 1.1rem;
		border: 1px solid var(--border-color);
		border-radius: 8px;
		background-color: color-mix(in srgb, var(--accent) 5%, transparent);
		color: var(--text);
	}
</style>
